# Generated by Django 3.0.6 on 2020-05-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('identificacion', models.PositiveIntegerField(unique=True, verbose_name='identificacion')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.BigIntegerField(verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=30, verbose_name='razon social')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('nit_cif', models.PositiveIntegerField(unique=True, verbose_name='NIT/CIF')),
                ('telefono', models.BigIntegerField(verbose_name='telefono')),
                ('persona_contacto', models.CharField(max_length=30, verbose_name='persona de contacto')),
                ('actividad_economica', models.CharField(max_length=100, verbose_name='actividad economica')),
                ('paginaweb', models.URLField(verbose_name='paginaweb')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('fax', models.BigIntegerField(verbose_name='fax')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedors',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
